runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: myAppId
  MASTER_KEY: myMasterKey
  # --OPTIONAL--
  # FILE_KEY: color-code
  # PARSE_MOUNT: /colorcode
  # CLOUD_CODE_MAIN:  